jobs:
  setup:
    steps:
      - buildevents/start_trace
    docker:
      - auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
        image: trussworks/circleci:caa7ee5c649b541f3fde6473d32b045bcfdb93ef
  watch:
    steps:
      - buildevents/watch_build_and_finish
    docker:
      - auth:
          password: $DOCKER_PASSWORD
          username: $DOCKER_USERNAME
        image: trussworks/circleci:caa7ee5c649b541f3fde6473d32b045bcfdb93ef
version: 2.1
workflows:
  validate:
    jobs:
      - setup:
          context:
            - org-global
      - watch:
          context:
            - org-global
          requires:
            - setup
  version: 2.1
orbs:
  buildevents: honeycombio/buildevents@0.2.7
